package com.kghospital.audit.domain.enums;

public enum OrderAction {
    ORDER_CREATED, ORDER_MODIFIED, ORDER_CANCELLED,
    ORDER_VERIFIED, ORDER_DISPENSED, ORDER_ADMINISTERED,
    ORDER_SUSPENDED, ORDER_RESUMED, ORDER_COSIGNED, ORDER_PRINTED
}
